live_config_reload = true

import = ["~/.config/alacritty/themes/catpuccin.toml"]

[window]
opacity = 0.60
blur = true
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 20
y = 15

[font]
size = 11 

[font.offset]
x = 1

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[cursor]
thickness = 0.1
