return {
  -- "folke/noice.nvim",
  -- event = "VeryLazy",
  -- opts = {},
  -- dependencies = {
  --   -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
  --   "MunifTanjim/nui.nvim",
  --   "rcarriga/nvim-notify",
  -- },
  -- config = function()
  --   require("notify").setup {
  --     icons = {
  --       ERROR = "[E]",
  --       WARN = "[W]",
  --       INFO = "[I]",
  --       DEBUG = "[D]",
  --       TRACE = "[T]",
  --     },
  --   }
  --   --vim.notify = require("notify")
  --
  --   require("noice").setup {
  --     lsp = {
  --       progress = {
  --         enabled = false,
  --       },
  --       -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
  --       override = {
  --         ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --         ["vim.lsp.util.stylize_markdown"] = true,
  --         ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
  --       },
  --     },
  --     -- you can enable a preset for easier configuration
  --     -- presets = {
  --     --   bottom_search = true, -- use a classic bottom cmdline for search
  --     --   command_palette = false, -- position the cmdline and popupmenu together
  --     --   long_message_to_split = true, -- long messages will be sent to a split
  --     --   inc_rename = false, -- enables an input dialog for inc-rename.nvim
  --     --   lsp_doc_border = true, -- add a border to hover docs and signature help
  --     -- },
  --     cmdline = {
  --       format = {
  --         -- conceal: (default=true) This will hide the text in the cmdline that matches the pattern.
  --         -- view: (default is cmdline view)
  --         -- opts: any options passed to the view
  --         -- icon_hl_group: optional hl_group for the icon
  --         -- title: set to anything or empty string to hide
  --         cmdline = { pattern = "^:", icon = "❯❯", lang = "vim" },
  --         search_down = { kind = "search", pattern = "^/", icon = "ᐯ ", lang = "regex" },
  --         search_up = { kind = "search", pattern = "^%?", icon = "ᐱ ", lang = "regex" },
  --         filter = { pattern = "^:%s*!", icon = "$", lang = "bash" },
  --         lua = { pattern = { "^:%s*lua%s+", "^:%s*lua%s*=%s*", "^:%s*=%s*" }, icon = "❯❯", lang = "lua" },
  --         help = { pattern = "^:%s*he?l?p?%s+", icon = "❯❯" },
  --         input = { view = "cmdline_input", icon = "❯❯ " }, -- Used by input()
  --         -- lua = false, -- to disable a format, set to `false`
  --       },
  --     },
  --     views = {
  --       cmdline_popup = {
  --         position = {
  --           row = 8,
  --           col = "50%",
  --         },
  --         size = {
  --           width = 60,
  --           height = "auto",
  --         },
  --       },
  --       popupmenu = {
  --         relative = "editor",
  --         position = {
  --           row = 100,
  --           col = "50%",
  --         },
  --         size = {
  --           width = 30,
  --           height = 10,
  --         },
  --         border = {
  --           style = "rounded",
  --           padding = { 0, 1 },
  --         },
  --         win_options = {
  --           winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
  --         },
  --       },
  --     },
  --   }
  -- end,
}
