format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$container\
$nix_shell\
$shell\
"""

palette = 'new'

[line_break]
disabled = true

[palettes.new]
purple = '#a670db'
base = '#70afdb'

[username]
style_user = "blue"
style_root = "red"
format = "[$user]($style) in "
disabled = false
show_always = true

[directory]
truncate_to_repo = true
style = "purple"

[git_branch]
symbol = ""
style = "cyan"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "red"
format = '([$all_status$ahead_behind]($style) )'

[nix_shell]
disabled = false
symbol = "NIX "
style = "yellow"
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '
