# BerlinNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#F2F2F2'

#[colors.cursor]
#cursor = '#F2F2F2'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = "#F07580"
green = "#80F075"
yellow = "#F0E575"
blue = "#7580F0"
magenta = "#A875F0"
cyan = "#75F0E6"
white = '#F2F2F2'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = "#F0A875"
