# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#b3c1cc'
foreground = '#1b2228'

# Normal colors
[colors.normal]
black = '#f2f2f2'
red = '#602025'
green = '#256020'
yellow = '#605a20'
blue = '#204560'
magenta = '#3a2060'
cyan = '#20605a'
white = '#0d0d0d'

# Bright colors
[colors.bright]
black = '#f2f2f2'
red = '#602025'
green = '#256020'
yellow = '#605a20'
blue = '#204560'
magenta = '#3a2060'
cyan = '#20605a'
white = '#0d0d0d'

# Search colors
[colors.search.matches]
foreground = '#ff007b'
background = '#f2f2f2'

[colors.search.focused_match]
foreground = '#f2f2f2'
background = '#ff007b'

# Selection colors
[colors.selection]
background = '#ff007b'
text = '#f2f2f2'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
[colors.cursor]
cursor = '#ff007b'
text = '#f2f2f2'

[colors.vi_mode_cursor]
cursor = '#ff007b'
text = '#f2f2f2'

[colors.footer_bar]
foreground = '#ff007b'
background = '#f2f2f2'

[[colors.indexed_colors]]
index = 93
color = '#3a2060'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#ff007b'
