live_config_reload = true

import = ["~/.config/alacritty/themes/flow-eclipse.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
blur = true
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 20
y = 15

[cursor]
thickness = 0.2

[font]
size = 11 

[font.offset]
x = 1
y = 7

[font.normal]
# family = "Cascadia Code"
# family = "BlexMono Nerd Font" # A Nerd version of IBM Plex
family = "Recursive Mono Linear Static" # A Nerd version of IBM Plex
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font" # A Nerd version of IBM Plex
style = "Bold"

[font.italic]
family = "Recursive Mono Casual Static" # A Nerd version of IBM Plex
style = "Italic"
