live_config_reload = true

import = ["~/.config/alacritty/themes/flow-eclipse.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
blur = true
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 20
y = 15

[cursor]
thickness = 0.1

[font]
size = 11 

[font.offset]
x = 1
y = 7

[font.normal]
family = "BlexMono Nerd Font" # A Nerd version of IBM Plex
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font" # A Nerd version of IBM Plex
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font" # A Nerd version of IBM Plex
style = "Italic"
