MD007: false
MD013:
  code_blocks: false
  line_length: 100
  # headings: false
  # tables: false


# Do not consider the frontmatter field `title`
# as an H1.
MD025:
  front_matter_title: ""

MD028: false
MD033: false
