# .prettierrc.toml
trailingComma = "es5"
tabWidth = 2
semi = false
singleQuote = true

[[overrides]]
files = "*.md"
[overrides.options]
tabWidth = 2
printWidth = 80
proseWrap = "always"
embeddedLanguageFormatting = "off"
